# Site settings
title: Adolygu Gloywi Iaith
email: palmergi1@cardiff.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  geraintpalmer
twitter_username: "@GeraintPalmer"

# Build settings
markdown: kramdown
permalink: pretty
syntax_highlighter: rouge

collections:
    pynciau:
        output: true
